### ISSUE TITLE
How To bulleted list formatting

### ISSUE THREAD

**Issue by terichadbourne** [ibm-cds-labs/dW#84] opened 2016-10-12 18:38 UTC
In Data Connect How Tos (for example, https://developer.ibm.com/clouddataservices2/docs/dataconnect/how-to/load-data-for-analytics/), there are lists of specific how to videos at the bottom.  It makes a > symbol to highlight which one you're currently on, but that symbol overlaps with the bullets and looks weird.

**Comment by terichadbourne** [comment] 2016-10-12 18:39
might be same as issue 78

**Comment by vabarbosa** [comment] 2016-10-12 20:55
duplicate of #78

**Closed as completed by vabarbosa** 2016-10-12 20:55 UTC
Labels: duplicate
