### ISSUE TITLE
Feature request: Enable Markdown on Dev Advo Blog

### ISSUE THREAD

**Issue by mmcelaney** [ibm-cds-labs/dW#143] opened 2016-10-25 16:28 UTC
This would be a HUGE timesaver for folks who are writing their blog posts via markdown in github so that we don't have to spend so much time updating the formatting to HTML tags when it's time to move the blog over to the wp template.

**Comment by jessmantaro** [comment] 2016-11-01 19:12
We had it enabled for our previous site version. I just turned it on again. Sometimes causes extra returns in our html copy, but I looked around and everything looks fine. The bigger problem is that the code snippets don't work. It's not just that we loose the syntax highlighting, it's that it gets all messed up. Here's how an xml snippet renders:

![xml_in_md](https://cloud.githubusercontent.com/assets/12279008/19903445/103abfa0-a045-11e6-9159-ac37641dd0d1.png)

So perhaps markdown could work for text only posts that don't contain chunks of code.

**Comment by mikebroberg** [comment] 2016-11-02 15:19
Agree that it made the styling on our last site wonky when we enabled Markdown. But the snippet you just shared -- isn't the solution _not_ to escape special characters? Or is that the problem?: that it's escaping characters that weren't escaped to begin with?

**Comment by jessmantaro** [comment] 2016-11-07 18:36
The problem is that is escapes special characters on its own.

**Comment by jessmantaro** [comment] 2016-11-07 18:38
Markdown is on and works well for simple posts. for code snippets, or more complicated layout/features (like a right-aligned thumbnail with caption, for example), we can use html. Closing this issue.

**Closed as completed by jessmantaro** 2016-11-07 18:38 UTC
